// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.0.0
//      Runtime Version:4.0.30128.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace LinqTwit.QueryModule.Tests.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OAuth Login")]
    public partial class OAuthLoginFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OAuthLoginFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OAuth Login", "In order to log in to Twitter\r\nAs a user\r\nI want to log in using OAuth", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get authorization URL")]
        [NUnit.Framework.CategoryAttribute("oauth")]
        public virtual void GetAuthorizationURL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get authorization URL", new string[] {
                        "oauth"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("a new OAuth login dialog");
#line 9
testRunner.And("the Oauth service returns an URL");
#line 10
testRunner.When("I have pressed the Authorize button");
#line 11
testRunner.Then("the system should retrieve the authorization URL");
#line 12
testRunner.And("launch it in the browser");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Show pin")]
        [NUnit.Framework.CategoryAttribute("oauth")]
        public virtual void ShowPin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show pin", new string[] {
                        "oauth"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("a new OAuth login dialog");
#line 17
testRunner.And("the Oauth service returns an URL");
#line 18
testRunner.When("I have pressed the Authorize button");
#line 19
testRunner.Then("the system should display textbox for inputting pin");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
